### ISSUE TITLE
Investigate solr document ranking changes for SW index sw-dev

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/sw_index_tests#171]

**Comment by cbeer** [comment]
The default similarity metric changed from `ClassicSimilarity` (nee `DefaultSimilarity`) to a newer `BM25Similarity`. For a first pass, we pinned to `ClassicSimilarity`, even though the new similarity metrics may improve document ranking (at the cost of a larger relevancy diff).

That said, there have been changes to the `ClassicSimilarity` metric as well, including a change in the lucene similarity metric (see https://issues.apache.org/jira/browse/LUCENE-6711). Instead of calculating the TF*IDF based on the number of documents in the index, they're now calculating it based on the number of documents with that particular field. This seems to elevate documents with less-common terms and potentially hits from less-common fields.

I think it's useful to test against `ClassicSimilarity` at first, in order to reassure ourselves that relevancy shifts are less likely to be indexing problems, but we may want to consider the improved similarity metrics before sending it out for evaluation.

**Comment by cbeer** [comment]
I'll also add that, using `ClassicSimilarity`, the relevancy changes seem usually to be +/-2 positions in most cases, with more dramatic changes for low-score search results (or where the top documents are hardly different).

**Comment by cbeer** [comment]
Most of the major document ranking changes occur in fielded search requests (Series, Subject, Author, etc), especially when there wasn't much to differentiate documents in the first place, so really tiny changes to relevancy calculations end up having a huge impact, but probably not in a way that impacts the end user.

**Comment by cbeer** [comment]
Another place we've seen ranking changes occur is for known-item searches, e.g. https://sul-solr-tester.stanford.edu/searches/94320. The exact-match result (or results) still rank at the top (usually in the same position), but the lower-quality hits are impacted by a change in the score calculation no longer adding additional boosts to multiple matches (that is, before you'd get a boost for matching an exact title, a stemmed title, the uniform title, etc, etc.. and in the new index, the score is determined mostly by the most-relevant match in the set)
